services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    container_name: web
    environment:
      MYSQL_DATABASE: my_db
      MYSQL_USER: user
      MYSQL_PASSWORD: /run/secrets/dev_user_password
    secrets:
      - db_root_password
      - dev_user_password
    ports:
      - "8800:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
      MYSQL_DATABASE: my_db
      MYSQL_USER: user
      MYSQL_PASSWORD: /run/secrets/dev_user_password
    secrets:
      - db_root_password
      - dev_user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  mysql_data:
    {}
secrets:
  db_root_password:
    file: db_root_password.txt
  dev_user_password:
    file: dev_user_password.txt